### ISSUE TITLE
webpack 4 support

### ISSUE THREAD

**Issue by zanettin** [egoist/interpolate-html-plugin#5]
hi

just wanted to ask, if you have plans to upgrade the api to support webpack 4 in the near future 😄  thanks for this great plugin!

**Comment by egoist** [comment]
Sure if we have to change something to make it work

**Comment by zanettin** [comment]
sry just found out, that i am using the react-dev-utils version directly and not your fork 😄 
but yes, seams like a hook has changed on webpack 4:

```
Error: Plugin could not be registered at 'html-webpack-plugin-before-html-processing'. Hook was not found.
BREAKING CHANGE: There need to exist a hook at 'this.hooks'. To create a compatiblity layer for this hook, hook into 'this._pluginCompat'.
    at Compilation.plugin (/Users/development/my-project/node_modules/tapable/lib/Tapable.js:63:9)
    at Compilation.deprecated [as plugin] (internal/util.js:52:15)
    at compiler.plugin.compilation (/Users/development/my-project/node_modules/react-dev-utils/InterpolateHtmlPlugin.js:26:19)
    at SyncHook.eval [as call] (eval at create (/Users/development/my-project/node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:7:1)
    at SyncHook.lazyCompileHook [as _call] (/Users/development/my-project/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.newCompilation (/Users/development/my-project/node_modules/webpack/lib/Compiler.js:400:26)
    at hooks.beforeCompile.callAsync.err (/Users/development/my-project/node_modules/webpack/lib/Compiler.js:432:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/development/my-project/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/development/my-project/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.compile (/Users/development/my-project/node_modules/webpack/lib/Compiler.js:427:28)
    at compiler.hooks.watchRun.callAsync.err (/Users/development/my-project/node_modules/webpack/lib/Watching.js:74:18)
    at _err4 (eval at create (/Users/development/my-project/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:35:1)
    at compilerInvalid (/Users/development/my-project/node_modules/webpack-dev-middleware/lib/Shared.js:161:5)
    at _err2 (eval at create (/Users/development/my-project/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:31:1)
    at /Users/development/my-project/node_modules/hard-source-webpack-plugin/index.js:1639:5
    at _err1 (eval at create (/Users/development/my-project/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:17:1)
✨  Done in 2.43s.
```

**Comment by abelino** [comment]
I believe the only thing that needs to be done is getting rid of the callback, https://github.com/egoist/interpolate-html-plugin/blob/master/index.js#L45

A cb is no longer supplied since the hook is called sync.

@zanettin to solve the error you are getting, define `InterpolateHtmlPlugin` after `HtmlWebpackPlugin` in the `plugins` array like so:

```
plugins: [
    new HtmlWebpackPlugin({
      template: './src/assets/templates/index.html.tmpl',
    }),
    new InterpolateHtmlPlugin({
      PUBLIC_URL: process.env.PUBLIC_URL || '',
    }),
  ],
```

Hope this helps to get the ball rolling.

**Comment by zanettin** [comment]
@abelino: thx! saw that on another example a few days ago and yes it fixed the problem. thx again for your hint

**Comment by k4mr4n** [comment]
I have problem with webpack 4 and I did @abelino solution but didn't work
```
ERROR in   TypeError: callback is not a function

  - index.js:45 compilation.plugin
    [static-pages]/[interpolate-html-plugin]/index.js:45:11


  - new Promise


  - Hook.js:35 AsyncSeriesWaterfallHook.lazyCompileHook [as _promise]
    [static-pages]/[tapable]/lib/Hook.js:35:21

  - index.js:647
    [static-pages]/[html-webpack-plugin]/index.js:647:47

  - index.js:175 Promise.resolve.then.then.then.then.then.then.html
    [static-pages]/[html-webpack-plugin]/index.js:175:18


  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7
```
and my webpack config file is: 
```
plugins: [
      new HtmlWebpackPlugin({
        template: `./public/index.${staticPageToBundle}.html`
      }),
      new InterpolateHtmlPlugin(obj),
      new webpack.HotModuleReplacementPlugin()
    ],
```

**Comment by abelino** [comment]
@k4mr4n updating the plugins array in webpack config is only part of the solution. The maintainer needs to update their codebase. The error you are getting: `callback is not a function`, means that a callback is no longer supplied as part of this interface https://github.com/egoist/interpolate-html-plugin/blob/master/index.js#L35

The code deff needs updating. cc @egoist

**Comment by k4mr4n** [comment]
@abelino I found the solution with another plugin which had same problem with webpack 4
https://github.com/van-nguyen/webpack-cdn-plugin/pull/18/files

**Comment by abelino** [comment]
@k4mr4n can you provide a PR. I'm a bit jammed atm. If you can't I'll try to get to this later tonight.

**Comment by k4mr4n** [comment]
@abelino sure I'll do but how can I test/run it in dev?

**Comment by egoist** [comment]
master branch has been updated to support webpack 4, npm is down now so I can't publish it yet 😅

**Comment by k4mr4n** [comment]
@egoist thank you
can you please help me know how can I contribute on these projects?
I know how to clone and submit PR but Idk how to test these projects in local
do you have any docs?

**Comment by abelino** [comment]
haha that npm always going down.  @egoist thanks for fixing this. @k4mr4n fyi when forking and testing locally you can use `npm link` https://docs.npmjs.com/cli/link to link a local package to a global namespace.

**Comment by abelino** [comment]
Other method is to require the local package via require statement + full path to the package in your local fs

**Comment by abelino** [comment]
ping @egoist could you publish latest version please? thanks

**Comment by egoist** [comment]
@abelino already published 😅
